# Generated by Django 3.2.5 on 2023-01-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='doB',
            field=models.DateField(),
        ),
    ]
