# Generated by Django 3.2.5 on 2023-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_alter_students_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_duretion',
            field=models.CharField(default='6 month', max_length=15),
        ),
    ]
